Story: API call Exchange Service (GET /catalogue)
UKHO/sales-catalogue-stub pull request #26
Opened 2021-03-12 12:28 UTC by tomling

- GetCatalogue in ProductEditionService returns latest baseline, releasable versions for all products.
- GetCatalogue on CatalogueApiController implemented to call service methods.
- Unit tests around service and controller methods.
- Refactored existing logic to use async

2021-03-15 15:05 UTC, bonpoole approved these changes

2021-03-16 10:33 UTC, UKHOGreg requested changes
Really good, just a couple things!

2021-03-16 10:33 UTC, UKHOGreg commented on src/UKHO.SalesCatalogueStub.Api/Services/ProductEditionService.cs
> +            return enc;
Are any `using` statements required here?

2021-03-16 10:33 UTC, UKHOGreg commented on src/UKHO.SalesCatalogueStub.Api/Services/ProductEditionService.cs
> +        }
Can we make this `async`?

2021-03-16 10:33 UTC, UKHOGreg commented on src/UKHO.SalesCatalogueStub.Api/Controllers/CatalogueApiController.cs
> +            var catalogueModified = _productEditionService.CheckIfCatalogueModified(ifModifiedSince, out var dateEntered);
Can we make this `async`?

2021-03-16 10:33 UTC, UKHOGreg commented on src/UKHO.SalesCatalogueStub.Api.Tests/ProductEditionServiceGetCatalogueTests.cs
> +        }
Can we move these to the top of the class, just underneath the fields please?

2021-03-16 11:43 UTC, tomling commented on src/UKHO.SalesCatalogueStub.Api/Services/ProductEditionService.cs
> +        }
Resolved, thanks!

2021-03-16 11:43 UTC, tomling commented on src/UKHO.SalesCatalogueStub.Api/Controllers/CatalogueApiController.cs
> +            var catalogueModified = _productEditionService.CheckIfCatalogueModified(ifModifiedSince, out var dateEntered);
Resolved, thanks!

2021-03-16 11:46 UTC, tomling commented on src/UKHO.SalesCatalogueStub.Api.Tests/ProductEditionServiceGetCatalogueTests.cs
> +        }
Resolved, thanks!

2021-03-16 11:51 UTC, tomling commented on src/UKHO.SalesCatalogueStub.Api/Services/ProductEditionService.cs
> +            return enc;
Resolved, thanks!

2021-03-16 13:38 UTC, UKHOGreg approved these changes

2021-03-17 09:51 UTC, merged